image: rikorose/gcc-cmake:gcc-8

stages:
  - build
  - release

compile:
  stage: build
  script:
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/release -DBUILD_EXAMPLES:BOOL=OFF
    - cmake --build . --parallel --config Release

release:
  stage: release
  only:
    - tags
  script:
    - mkdir ./release
    - cmake --install . --config Release
  artifacts:
    paths:
      - release
    name: iklibs-release
