image: "ghcr.io/rikorose/gcc-cmake:latest"

stages:
  - build
  - release

compile:
  stage: build
  script:
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/release -DBUILD_EXAMPLES:BOOL=OFF -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Wconversion -Wsign-conversion" .
    - cmake --build . --config Release -j 4
  artifacts:
    paths:
      - ./*
    expire_in: 1h

cppcheck:
  stage: build
  script:
    - apt-get update -qq
    - apt-get install -y -qq cppcheck
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
    - cppcheck --project=compile_commands.json &> cppcheck-report.txt
  artifacts:
    paths:
      - cppcheck-report.txt

binaries:
  stage: release
  only:
    - tags
  script:
    - mkdir ./release
    - cmake --install . --config Release
  artifacts:
    paths:
      - release
    name: iklibs-release

documentation:
  stage: release
  only:
    - tags
  image: hrektts/doxygen
  script:
    - doxygen Doxyfile
  artifacts:
    paths:
      - html
    name: html-doc
